SELECT COUNT(*) AS "QTD CLIENTES" FROM FUNCIONARIO WHERE NUM_AG = 0001;



SELECT TRANSACAO.DATA_TRANS AS DATA, TRANSACAO.VALOR, TRANSACAO.TIPO, TRANSACAO.NUM_CONTA, CLIENTE.CPF_CLI
FROM TRANSACAO
JOIN CONTA ON TRANSACAO.NUM_CONTA = CONTA.NUM_CONTA
JOIN CLIENTE ON CONTA.CPF_CLI = CLIENTE.CPF_CLI;



SELECT SUM(SALDO) AS "Receita total do banco" FROM CONTA;



SELECT TRANSACAO.TIPO AS "TIPO TRANSAÇÃO", MAX(TRANSACAO.VALOR) AS "VALOR MÁXIMO"
FROM TRANSACAO
JOIN CONTA ON TRANSACAO.NUM_CONTA = CONTA.NUM_CONTA
GROUP BY TRANSACAO.TIPO;



SELECT * FROM FUNCIONARIO WHERE CARGO LIKE 'Gerente%';
